name: Scrape latest vehicle reports data

on:
  push:
  workflow_dispatch:
  schedule:
    # triggered every 1st of every month at 11am UTC.
    - cron: '0 11 1 * *' 

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@main
    - name: Fetch latest data
      run: |-
        curl https://nyc.gov/site/nypd/stats/reports-analysis/vehicle-stop-reports.page > vehicle_stops.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
